---
title: "TP1 - Criminalité à Toronto"
author: "groupe B"
output: github_document
---

### Chargement librairies
```{r load-packages, message=FALSE}
library(tidyverse) 
library(dsbox) 
library(corrplot)
library(dplyr)
library(readxl)
library(outliers)
library(ggplot2)
```

### Chargement datasets

```{r load-data, message=FALSE}
budget <- read_csv("data/Budget_2022.csv")
Major_Crime <- read_csv("data/Major_Crime_Indicators.csv")
properties <- read_csv("data/properties.csv")
```
### Résummer des données

```{r fonction, message=FALSE}

my_summary <- function(x) {
  if(is.character(x) == TRUE)
  {
    uniqv <- unique(x)
    output1 = uniqv[which.max(tabulate(match(x, uniqv)))]
    names(output1) <- "mode"
    output2 = table(x)[output1]/length(x)
    names(output2) <- "freq"
    
    y <- x[x!=output1]
    uniqv <- unique(y)
    output3 = uniqv[which.max(tabulate(match(y, uniqv)))]
    names(output3) <- "mode 2"
    output4 = table(y)[output3]/length(x)
    names(output4) <- "freq 2"
    
    if(!is.na(output3))
    {
      return(c(output1,output2,output3,output4))
    }
    return(c(output1,output2))
  }
  if(is.numeric(x) == TRUE)
  {
    output1 <- summary(x)
    output2 <- sd(x)
    names(output2) <- "Ecart type"
    if(is.na(output2))
    {
        return(c(output1, output2))
    }
    output3 <- quantile(x)[4] - quantile(x)[2]
    names(output3) <- "IQR"
    
    output4 <- range(x)[2] - range(x)[1]
    names(output4) <- "Etendue"
    
    output5 <- var(x)
    names(output5) <- "Variance"
    
    output6 <- output2 / mean(x)
    names(output6) <- "coeficient de variation"
    
    return(c(output1, output2, output3,output4, output5, output6))
  }
  }

```

```{r summary, message=FALSE}
sapply(budget,my_summary)
sapply(Major_Crime,my_summary)
sapply(properties,my_summary)
```





```{r}
select_numeric_cols <- function(df) {
  numeric_cols <- sapply(df, is.numeric) # Détermine les colonnes numériques
  df_numeric <- df[, numeric_cols] # Sélectionne les colonnes numériques
  return(df_numeric) # Retourne le dataframe avec les colonnes numériques uniquement
}
```


```{r}
propertie_num <- select_numeric_cols(properties)
print(propertie_num)
```

```{r}
cor(propertie_num)
```
```{r}
cor_pro_num = cor(propertie_num)
```

```{r}
corrplot(cor_pro_num, type = "upper", order = "hclust", tl.col = 'black', tl.srt = 45)
```

```{r}
budget_num <- select_numeric_cols(budget)

```

```{r}
remove_variable <- function(data, var_name) {
  data[, var_name] <- NULL
  return(data)
}

budget_num2<- remove_variable(budget_num, "Fiscal_Year")
```


```{r}
cor(budget_num2)
```
```{r}
cor_bud2_num = cor(budget_num2)
```

```{r}
corrplot(cor_bud2_num, type = "upper", order = "hclust", tl.col = 'black', tl.srt = 45)
```


```{r}
Major_Crime_num <- select_numeric_cols(Major_Crime)
```

```{r}
Major_Crime_num2<- remove_variable(Major_Crime_num, "occurrenceyear")
Major_Crime_num3<- remove_variable(Major_Crime_num2, "occurrenceday")
Major_Crime_num4<- remove_variable(Major_Crime_num3, "occurrencedayofyear")


```


```{r}
cor(Major_Crime_num4)
```

```{r}
cor_maj4_num = cor(Major_Crime_num4)
```

```{r}
corrplot(cor_maj4_num, type = "upper", order = "hclust", tl.col = 'black', tl.srt = 45)
```

### Visualisation

```{r}
Major_Crimetest <- Major_Crime %>% mutate(
  offence = case_when(substr(offence,1,7) == "Assault" ~ "Assault",
                      substr(offence,1,10) == "Aggravated" ~ "Assault",
                      substr(offence,1,3) == "B&E" ~ "B&E",
                      substr(offence,1,7) == "Robbery" ~ "Robbery",
                      substr(offence,1,5) == "Theft" ~ "Robbery",
                      substr(offence,1,9) == "Discharge" ~ "Firearm",
                      substr(offence,1,3) == "Use" ~ "Firearm",
                      substr(offence,1,8) == "Pointing" ~ "Firearm",
                      substr(offence,1,3) == "Air" ~ "Firearm",
                      TRUE ~ offence))

Major_Crimetest$offence <- fct_infreq(Major_Crimetest$offence)

ggplot(Major_Crimetest) +
  aes(x = offence) +
  geom_bar(fill = "#112446") +
  theme_minimal()+
  labs(x = "Type d'infractions", y = "Nombre", title = "classement des types infractions à Toronto")
```




```{r}
budget %>%
 filter(!(Command_Name %in% "Information&Technology Command (Command)")) %>%
 filter(!(Pillar_Name %in% 
 c("Centralized Service Chrgs & UNS (Pillar)", "Professionalism & Accountability (Pillar", "Finance & Business Mgmt (Pillar)", 
 "People & Culture (Pillar)", "Information&Technology Command (Pillar)", "Combat Gun&Gang Violence Grant (Pillar)", 
 "Community Safety&Policing Grant (Pillar)", "Provincial Guns&Gangs Grnt2 (Pillar)", "Community Safety&Policing Grnt2 (Pillar)"
 ))) %>%
 filter(!(Feature_Category %in% "Materials & Supplies")) %>%
 ggplot() +
  aes(x = Feature_Category, y = Amount) +
  geom_col(fill = "#112446") +
  theme_minimal()+
  labs(x = "catégorie de fonctionnalités", y = "montant", title = "gestion de finance de la police de Toronto")
```

```{r}
Major_Crimetest <- Major_Crimetest[Major_Crime$X != 0,]
Major_Crimetest <- Major_Crimetest[Major_Crimetest$reportedmonth =="January",]
Major_Crimetest <- Major_Crimetest[Major_Crimetest$reportedday < 5,]
Major_Crimetest <- Major_Crimetest[Major_Crimetest$X > -8870000,]
Major_Crimetest <- Major_Crimetest[Major_Crimetest$Y < 5440000,]

ggplot(Major_Crimetest, mapping = aes(x = X, y = Y, color = offence)) +
  geom_point(alpha = 0.5)+
  labs(x = "Longitude", y = "Latitude", title = "Crime à Toronto")

```


```{r}

propertiestest <- properties[properties$lng > -85,]
propertiestest <- propertiestest[propertiestest$lng < -73,]
propertiestest <- propertiestest[propertiestest$lat < 46.5,]
colnames(propertiestest)[4] <- "Price"

ggplot(propertiestest) +
  aes(x = lng, y = lat, colour = Price) +
  geom_point(shape = "circle", size = 1.5) +
  scale_color_distiller(palette = "Set1", direction = 1) +
  theme_minimal()+
  labs(x = "Longitude", y = "Latitude", title = "Ventes Immobilière à Toronto")


```



```{r}
#On regarde la présence d'outliers pour la dataset properties
test <- grubbs.test(properties$`Price ($)`)
test

test <- grubbs.test(properties$`Price ($)`, opposite= TRUE)
test

boxplot(properties$`Price ($)`)

#On peut voir la forte présence d'outliers sur le boxplot par l'apparition de points noirs. 

mediane <- median(properties$`Price ($)`, na.rm=TRUE)
properties$`Price ($)` <- ifelse(properties$`Price ($)` > quantile(properties$`Price ($)`, 0.75) + 1.5 * IQR(properties$`Price ($)`) | properties$`Price ($)` < quantile(properties$`Price ($)`, 0.25) - 1.5 * IQR(properties$`Price ($)`), mediane, properties$`Price ($)`)
#On remplace par la médiane les outliers qu'on a détecté par le calcul de l'équart type.

boxplot(properties$`Price ($)`)
#On peut voir que les outliers sont moins nombreux. Il reste quelque point noir mais qui ne sont pas concidéré comme des outliers.
```

```{r analyse}
# On analyse uniquement les colonnes ou il y a possiblement des erreurs.

table(Major_Crime$X)
table(Major_Crime$Y)
#On peut voir la présence de 0 dans les colonnes en X et en Y qui se répète par la suite aussi dans la longitude et lattitude
table(Major_Crime$reportedyear)
table(Major_Crime$reportedmonth)
table(Major_Crime$reportedday)
table(Major_Crime$reporteddayofweek)
table(Major_Crime$reportedhour)
#Il n'y a pas présence d'outliers ici
table(Major_Crime$location_type)
#On peut voir la présence d'une catégorie Unknow qui pourrait être un outliers mais qui pourrait juste être par exemple des enquêtes non élucidées ou des cadavres non retrouvé. 


#Après analyse de chacune des variables présentes dans les différentes colonnes nous avons pu remarqué dans la colonne Y la présence de données étant égales a 0 ce qui est impossible pour la colonne X et Y car étant des coordonnées.
```
 
```{r}
#Comme on a constaté la présence de 0 sur la colonne Y a l'aide de cette fonction nous allons donc supprié toute la ligne.
Major_Crime <- Major_Crime[Major_Crime$ Y!=0,]
```






